version: "3.8"
services:
  mongo:
    build:
      context: ./docker/mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: "27017"
      MONGO_COMMAND: 'mongosh'
    ports:
      - 27017:27017
    restart: always
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      DATABASE_URL: "mongodb://mongo:27017/db?authSource=admin&directConnection=true"
      PORT: 5050
    restart: always
    command: bash -c "npm run generate && npm start"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend